name: Release
on:
  push:
    branches:
      - main
      - beta
      - alpha
      - pre

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

env:
  HUSKY: 0

jobs:
  setup:
    name: Setup workflow
    runs-on: ubuntu-latest
    outputs:
      NODE_VERSION: ${{ steps.get-node-npm-version.outputs.NODE_VERSION }}
      PNPM_VERSION: ${{ steps.get-node-npm-version.outputs.PNPM_VERSION }}
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Get Node and PNPM version
        id: get-node-npm-version
        run: |
            echo "NODE_VERSION=$(cat package.json | jq -r '.volta.node')" >> $GITHUB_OUTPUT
            echo "PNPM_VERSION=$(cat package.json | jq -r '.packageManager' | awk -F'@' '{print $2}')" >> $GITHUB_OUTPUT

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
            version: ${{ needs.setup.outputs.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: ${{ needs.setup.outputs.NODE_VERSION }}
            cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i --prefer-offline

      - name: Check unit tests
        run: pnpm run test:unit

      - name: Build
        run: pnpm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CI_CD }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_CI_CD }}
          NPM_TOKEN: ${{ secrets.GH_CI_CD }}
        run: pnpm run release
